### ISSUE TITLE
 Could not open database environment; please check options and file system (corrupted) (error code -30796)

### ISSUE THREAD

**Issue by unengchen** [objectbox/objectbox-java#1016] opened 2021-10-27 07:43 UTC
:rotating_light: First, please check:
 - existing issues,
 - Docs https://docs.objectbox.io/
 - Troubleshooting page https://docs.objectbox.io/troubleshooting
 - FAQ page https://docs.objectbox.io/faq

**Describe the bug**
private var boxStore: BoxStore? = null
    fun initBox(context: Context) {
        boxStore = MyObjectBox.builder()
            .androidContext(context.applicationContext).build()

        if (BuildConfig.DEBUG) {
            AndroidObjectBrowser(boxStore).start(context)
        }
    }

fun getUserBox(): Box<User> = boxStore!!.boxFor(User::class.java)
    fun getFaceBox(): Box<Face> = boxStore!!.boxFor(Face::class.java)
    fun getFingerBox(): Box<Finger> = boxStore!!.boxFor(Finger::class.java)
    fun getLogBox(): Box<Log> = boxStore!!.boxFor(Log::class.java)

when to build the boxStore to occurred this problem . my application just one boxStore，has mutil entities.
error info :Could not open database environment; please check options and file system (corrupted) (error code -30796)

**Basic info (please complete the following information):**
 - ObjectBox version 2.9.1
 - Reproducibility: always occurred when start app
 - Device: rk3288
 - OS: Android 8.1

**Comment by greenrobot-team** [comment] 2021-11-02 09:10
Duplicate of #1015

**Closed by greenrobot-team** 2021-11-02 09:10 UTC
Labels: bug
