### ISSUE TITLE
Target entity in a ToOne relation not persisted with the parent entity if the target entity has an assignable id

### ISSUE THREAD

**Issue by RoqueCampos** [objectbox/objectbox-java#214] opened 2017-10-16 10:40 UTC
## Issue Basics
- ObjectBox version (are using the latest version?): 1.1.0
- Reproducibility: always

### Description

Not sure if this is a bug or the intended behaviour.

After deserializing a Json Object that contains a child object I want to store it as a ToOne relation in the objectbox database. For Example:

```
List<Order> orders= transporter.getValue();
for (Order order: orders) {
            order.media.setTarget(order.getMediaTransporter());
            boxStore.boxFor(Order.class).put(order);
}
```

Both entities (Order and Media) are entities with assignable Id's. Because of that, the function 
public boolean internalRequiresPutTarget(), in the ToOne class returns always false (because the id is not 0). and the inner object is not persisted in the database.

## Entities

```
@Entity
public class Media {

    @Id(assignable = true)
    private Long id;
    private String relativePath;

(...)

@Entity
public class Order {

    @Id(assignable = true)
    private Long id;
    public ToOne<Media> media;

(...)
```

The workaround is to explicitly put the media entity before putting the Order entity... As said, I don't know if this is the intended behaviour. If this is not a bug, then I request apologizes!

Regards!

**Comment by greenrobot-team** [comment] 2017-10-17 08:30
For now I would say this is working as intended as it is geared towards the default behavior. Have a look at http://objectbox.io/documentation/entity-annotations/#Object_IDs_Id

To handle this ObjectBox would need to differentiate between "regular" entities and those that can have manually assigned IDs. -ut

**Comment by greenrobot-team** [comment] 2020-09-08 13:53
Closing this for now as won't fix. Based on feedback we might improve/change behavior when using assigned IDs in the future.

**Closed by greenrobot-team** 2020-09-08 13:53 UTC
