### ISSUE TITLE
java.lang.LinkageError: Loading ObjectBox native library failed when running with Robolectric

### ISSUE THREAD

**Issue by cincospenguinos** [objectbox/objectbox-java#847] opened 2020-04-13 00:20 UTC
## Issue Basics
- ObjectBox version (are using the latest version?): *2.5.1*
- Reproducibility: *always*

## Reproducing the bug

1. Load Roboelectric into your test suite
2. Create a Roboelectric unit test that tests a random view or activity
3. Create a totally separate unit test that builds an ObjectBox DB and tests entities
4. Run all of them together (I used android studio's `ctrl+shift+f10` on the unit test package)
5. Observe all of the errors that occur after Roboelectric unit tests run

### Description

A variety of exceptions all centering around a missing Windows .dll are thrown. Running the entity test classes in isolation causes them all to pass, and running the view test classes in isolation makes them all pass, but running all of them together causes all of the entity tests to fail.

### Code

`build.gradle`:
```gradle
...
dependencies {
    ....
    testImplementation 'junit:junit:4.13'
    testImplementation 'org.robolectric:robolectric:4.3'
    testImplementation "org.mockito:mockito-core:2.25.0"
    testImplementation "io.objectbox:objectbox-windows:$objectboxVersion"
}
```

`EntityTest.java`:
```java
public class EntityTest {
    protected static final File TEST_DIRECTORY = new File("objectbox-test-db");
    protected BoxStore store;

    @Before
    public void setUp() {
        BoxStore.deleteAllFiles(TEST_DIRECTORY);
        store = MyObjectBox.builder()
            .directory(TEST_DIRECTORY)
            .debugFlags(DebugFlags.LOG_QUERIES | DebugFlags.LOG_QUERY_PARAMETERS)
            .build(); // NOTE: This is where the failure happens
    }

    @After
    public void tearDown() {
        if (store != null) {
            store.close();
            store = null;
        }

        BoxStore.deleteAllFiles(TEST_DIRECTORY);
    }

    // ...
}
```

`ViewTest.java`:
```java
public class ViewTest {
    @Before
    public void setup() {
        ActivityController<Activity> activityController = Robolectric.buildActivity(Activity.class);
        Activity activity = activityController.get();
        view = new ValidatedTextView(activity);
    }

    // ...
}
```

### Logs & stackstraces

```
java.lang.LinkageError: Loading ObjectBox native library failed: vendor=JetBrains s.r.o,os=windows 10,os.arch=amd64,sun.arch=64,android=false,linux=false

	at io.objectbox.internal.NativeLibraryLoader.<clinit>(NativeLibraryLoader.java:109)
	at io.objectbox.BoxStore.<init>(BoxStore.java:199)
	at io.objectbox.BoxStoreBuilder.build(BoxStoreBuilder.java:383)
	at com.stoicapps.roll4initiative.ObjectBoxTestBase.setUp(ObjectBoxTestBase.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.UnsatisfiedLinkError: Native Library C:\Users\alafleur\AndroidStudioProjects\Roll4Initiativev1\app\objectbox-jni-windows-x64.dll already loaded in another classloader
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1907)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at io.objectbox.internal.NativeLibraryLoader.<clinit>(NativeLibraryLoader.java:78)
	... 39 more
```

```
java.lang.NoClassDefFoundError: Could not initialize class io.objectbox.internal.NativeLibraryLoader

	at io.objectbox.BoxStore.<init>(BoxStore.java:199)
	at io.objectbox.BoxStoreBuilder.build(BoxStoreBuilder.java:383)
	at com.stoicapps.roll4initiative.ObjectBoxTestBase.setUp(ObjectBoxTestBase.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

## Entities

The entities don't seem to be relevant to this app.

## Misc

* Workaround: simply run tests separately when developing. I don't have a CI configuration though--if I did, this would probably be a full blocker for me.
* This seems related if not identical to both #789 and #482

**Comment by greenrobot-team** [comment] 2020-04-20 05:44
Thanks for reporting.

The culprit is `Caused by: java.lang.UnsatisfiedLinkError: Native Library C:\Users\alafleur\AndroidStudioProjects\Roll4Initiativev1\app\objectbox-jni-windows-x64.dll already loaded in another classloader`.

Robolectric uses its own class loader. However a native library can only be loaded in one at a time.

Running all your unit tests with Robolectric should solve this. E.g. add `@RunWith(RobolectricTestRunner.class)` to the tests that fail:

```
/**
 * Note: runs with Robolectric to load ObjectBox native library in same class loader
 * (Robolectric uses its own class loader). This avoids the UnsatisfiedLinkException with
 * message "Native library already loaded in another classloader".
 */
@RunWith(RobolectricTestRunner.class)
public class LegacyObjectBoxTest {
```

To avoid loading the full application, you might also want to add `@Config(application = EmptyApplication.class)` and define `EmptyApplication` as an empty subclass of `Application`.

**Comment by greenrobot-team** [comment] 2020-08-03 13:40
Closing. Please re-open if your question was not answered.

**Closed by greenrobot-team** 2020-08-03 13:40 UTC
