### ISSUE TITLE
DbException when init ObjectBox with invoking method "initialDbFile"

### ISSUE THREAD

**Issue by AnswerZhao** [objectbox/objectbox-java#923] opened 2020-10-26 08:50 UTC
io.objectbox.exception.DbException: DB's last entity ID 21 is higher than 5 from model，when i init MyObjectBox with invoking initialDbFile method to use local data.mdb file.

**Comment by greenrobot-team** [comment] 2020-10-26 12:10
See the Troubleshooting page for this error.
https://docs.objectbox.io/troubleshooting#dbexception-after-switching-git-branch-no-concurrent-data-model-modifications

**Comment by AnswerZhao** [comment] 2020-10-27 02:37
One app init ObjectBox with initialDbFile method to load data.mdb file of another app, but the app does not have all Entity class required by this db, then it will have this trouble. 
Your link is another issue with changing DB entity. 
However I think the deep reason is same.
Thanks.

**Comment by greenrobot-team** [comment] 2020-10-27 07:13
Yes, the model in your app must match the model of the database. You can not use a database that has a different model. Closing this then as working as intended.

**Closed by greenrobot-team** 2020-10-27 07:13 UTC
Labels: bug
