### ISSUE TITLE
How do I open the .mdb file on PC?Because I'm going to get the data from the online app's database.

### ISSUE THREAD

**Issue by njzy63lys** [objectbox/objectbox-java#659] opened 2019-02-18 07:17 UTC
I looked at the website. https://docs.objectbox.io/data-browser
But it couldn't meet my needs.I want to confirm whether the data in the online app is correct and how to open it with the computer after obtaining the mdb file of the online app.If i have an mdb file, then place it in the location specified by the emulator and open it through a browser, this is too complicated.
Can you give me a good solution? Thank you very much.

**Comment by greenrobot-team** [comment] 2019-02-18 10:28
Looks like you should thumbs up https://github.com/objectbox/objectbox-java/issues/519

Closing as duplicate of https://github.com/objectbox/objectbox-java/issues/519
-ut

**Closed by greenrobot-team** 2019-02-18 10:28 UTC
