### ISSUE TITLE
ToMany is automatically sorted by Entity id

### ISSUE THREAD

**Issue by zoltish** [objectbox/objectbox-java#431] opened 2018-04-15 07:32 UTC
## Issue Basics
- ObjectBox version (are using the latest version?): 1.4.4
- Reproducibility: Always

### Description
I have an Entity `ExerciseEntity` that contains a ToMany of `BodypartEntity`.

When creating a new ExerciseEntity, bodyparts are specified as A,B,C. Their ordering is important.

After inserting the entity into the Box, later on it will contain the bodyparts with a completely different order (e.g. B,A,C). From what I can tell theyre always sorted by their id annotated value.

### Code
ExerciseEntity has `lateinit var bodyparts: ToMany<BodypartEntity>` 
When creating a new one its assigned as `entity.bodyparts.addAll(bodyparts)`

**Comment by greenrobot-team** [comment] 2018-04-16 07:52
That items are ordered by ID when loaded from the store is by design, see the [docs on the method `ToMany.sortById()`](http://objectbox.io/files/objectbox-java/current/io/objectbox/relation/ToMany.html#sortById--). -ut

**Comment by zoltish** [comment] 2018-04-16 08:10
@greenrobot-team I see! In that case -> How can I keep my own insertion order?  

And out of curiosity, is it common to sort lists like this in storage solutions? I dont think Ive ever come across it prior to this, in my experience the natural order is the one theyre placed in when storing them?

**Comment by zoltish** [comment] 2018-04-16 17:31
**Thanks for the answers!** 👍 I think Ill end up including the list index inside the object wherever it makes sense as you mention!

**Comment by greenrobot-team** [comment] 2018-04-17 06:18
Closing this then. -ut

**Closed by greenrobot-team** 2018-04-17 06:18 UTC
