### ISSUE TITLE
Order query based on ToOne or ToMany

### ISSUE THREAD

**Issue by mntanproject** [objectbox/objectbox-java#963] opened 2021-03-17 04:05 UTC
Unable to add order based on relation field.
```
@Entity
public class Purchase {

@Id
public long id;
public float total;
public Date createdOn;

}
@Entity
public class Supplier {
    @Id
    public long id;
    public String company,name,contactno,email,street,city,state,country,bank,notes;
}

QueryBuilder<Purchase> query = objBox.query();
query.link(Purchase_.supplier).order(Supplier_.name);
List<Purchase> objects = query.build().find();

```
Throws Error:

```
Caused by: java.lang.IllegalStateException: This call is not supported on sub query builders (links)

```

**Comment by greenrobot-team** [comment] 2021-03-22 07:50
This is a duplicate of #141 if I read this right?

**Comment by mntanproject** [comment] 2021-03-22 08:18
Yes. It is the same issue ('Unable to sort based on relation's property') and it would be great to have this and #497 features. Workaround is to read all the results and sort it in the program, but that violates pagination where wanted to provide faster loading time to user. As reading all the data is slower and heavier workload, comparing to just pagination pages results.

**Comment by greenrobot-team** [comment] 2021-03-22 10:45
OK, closing this then as a duplicate. Please discuss further in #141.

**Closed by greenrobot-team** 2021-03-22 10:45 UTC
Labels: feature
