### ISSUE TITLE
Add put/remove that also removes related entities

### ISSUE THREAD

**Issue by tvvbbb** [objectbox/objectbox-java#526] opened 2018-08-14 14:14 UTC
```java
public class A{
ToMany<objectA> objectB;
}

public class b{
     A a;
}

```
How can I delete  a then relative objectA will delete auto?

**Comment by greenrobot-team** [comment] 2018-08-21 08:49
I'm sorry, but this example makes no sense to me.

In general: if you remove an entity from a `ToMany` and `put()`, only the relation is dissolved. You have to remove the related entity yourself:
```java
// remove relation to order from customer
Order order = customer.orders.remove(0);
boxStore.boxFor(Customer.class).put(customer);
// remove the order itself
boxStore.boxFor(Order.class).remove(order);
```

Closing. Please re-open if your question was not answered.
-ut

**Comment by tvvbbb** [comment] 2018-08-21 08:55
Why not remove related entities auto?

**Comment by greenrobot-team** [comment] 2018-08-27 12:29
Because you might not want to, for example to change a relation or to only temporarily remove the relation. So you have to explicitly do it yourself. -ut

**Comment by tvvbbb** [comment] 2018-08-27 12:31
I agree with you. But I think ObjectBox can also offer this option.

**Comment by greenrobot-team** [comment] 2018-08-28 05:49
Alright, re-opening. Please thumbs-up the issue if you want this feature. -ut

**Comment by greenrobot-team** [comment] 2019-01-08 07:34
Closing this as a duplicate of #79.
-ut

**Closed by greenrobot-team** 2019-01-08 07:34 UTC
Labels: feature
