### ISSUE TITLE
 Browser show db  content  have a bug 。 A long content 

### ISSUE THREAD

**Issue by njzy63lys** [objectbox/objectbox-java#500] opened 2018-07-13 07:10 UTC
## Issue Basics
- version  1.5.0 2.0.0-beta
- Reproducibility : always

### Description
* Browser show db  content  have a bug 。 A long content 

eg：
![objectboxbug](https://user-images.githubusercontent.com/15622457/42677618-daff1a46-86ae-11e8-8bb4-2ef721d3fc36.jpg)

**Comment by greenrobot-team** [comment] 2018-08-06 12:36
Thanks for reporting.

Can reproduce using our note example.

Web app is fine, the API already returns incorrect data.
-ut

**Comment by greenrobot-team** [comment] 2018-08-06 12:40
Also, when trying to filter for such a large value the API returns `{error: {code: 500, message: "stol: out of range"}}`.
-ut

**Comment by greenrobot-team** [comment] 2018-08-13 09:31
Just to give an update on this (working on this internally):
- the filter issue will be fixed with the next update
- the display issue is due to JavaScript not supporting 64bit signed integers, instead it uses floating point. You can get the correct numers by looking at the JSON download (JSON has no range limit on numbers). Still looking for a solution.

-ut

**Comment by greenrobot-team** [comment] 2018-08-13 12:25
The display bug was fixed internally (by sending non-floating point 64-bit numbers as JSON String). This should be available with the next update. -ut

**Closed by greenrobot-team** 2018-08-13 12:25 UTC
Labels: bug

**Comment by njzy63lys** [comment] 2018-08-16 09:11
@greenrobot-team   Thank you for your answer
