### ISSUE TITLE
default.json line break type

### ISSUE THREAD

**Issue by zhangguangxuan** [objectbox/objectbox-java#1017] opened 2021-10-29 09:02 UTC
Is there a function to specify the line break type when creating the default.json? e.g. LF, CR or CRLF.

**Comment by greenrobot-team** [comment] 2021-11-02 09:17
No there is not. I doubt one will be added.

Is there are reason you need this option?

**Comment by zhangguangxuan** [comment] 2021-11-02 09:28
The default.json is CRLF in our git server.

**Comment by greenrobot-team** [comment] 2021-11-09 14:13
Thanks! Closing this as a duplicate of #181 Please thumbs up that issue instead!

**Closed by greenrobot-team** 2021-11-09 14:13 UTC
Labels: feature
