### ISSUE TITLE
Skipped low-level close of cursor

### ISSUE THREAD

**Issue by qeadsw** [objectbox/objectbox-java#615] opened 2018-11-20 11:25 UTC
V2.2.0

Tips appear when added and modified through put()
[Skipped low-level close of cursor (write, TX #3 alive)]

Need to close or release some objects?

**Comment by greenrobot-team** [comment] 2018-11-20 13:01
Thanks for reporting. This is known. Duplicate of #196.
-ut

**Closed by greenrobot-team** 2018-11-20 13:01 UTC
