### ISSUE TITLE
Gson is not identifying ToMany 

### ISSUE THREAD

**Issue by dj-4war** [objectbox/objectbox-java#436] opened 2018-04-19 07:36 UTC
## Issue Basics
- ObjectBox version (are using the latest version?): *1.4.4*
- Gson library version  : 2.8.2
- Reproducibility: *always*

### Description
I have a List<CustomObj> that I get from server and I use Gson library to parse the entire object. 
My List<CustomObj> must be stored in the DB. So the model for the  ObjectBox will be 

@Entiry
class OBStoredObj{
@Id 
long id;

ToMany<CustomObj> list;
}
}

I am mapping the same above object to Gson library to parse the server result because ToMany is derived from  List<> (As per the documentation). I am getting below error that Gson is not understanding ToMany to parse. I understand that Gson does not have a class defination  of ToMany because its Object Box class. 

At the same point I dont want to create another dummy class with List<CustomObj> and loop through and the objects. I want the simple solution to make it work with the Gson. 

Logs : 
_has type io.objectbox.relation.ToMany, got java.util.ArrayList_

## Entities
@Entity
public class FileListResult {

    @Id
    public long id;

    public ToMany<FileModel> files;
}

@Entity
public class FileModel {

    @Id
    public long id;

    public String fName;
    public String fSize;
    public String fPath;
    public String fCheckSum;
    public String fExtension;

}

**Comment by greenrobot-team** [comment] 2018-04-23 05:43
Please see the discussion and issue tracking this: #104.

Closing this as duplicate of #104. -ut

**Closed by greenrobot-team** 2018-04-23 05:43 UTC

**Comment by dj-4war** [comment] 2018-10-12 05:33
Did we address this in latest version ?

**Comment by dj-4war** [comment] 2019-03-05 12:10
Did we address this ?

I see same issue with ToOne when we parse using Gson. 

This must be addressed, mobile does most of API operations if we have to do explicit  marshelling of objects will increase the dependencies in API call or we should build internal JSON object mapper like Retrofit.
