### ISSUE TITLE
New property does not have Kotlin default value when getting existing entity

### ISSUE THREAD

**Issue by jrcacd** [objectbox/objectbox-java#664] opened 2019-02-20 16:15 UTC
ObjectBox 2.3.3

In Kotin, when we create a field on an existing entity, the field on the existing records is not pupulated with the default value.

Example:

**Before**
Entity
```
data class Record(
        @Id var id: Long= 0,
        var uuid: String = "")
```

**After**
```
data class Record(
        @Id var id: Long= 0,
        var uuid: String = "",
        var date: Long = Date.now().toMillis()) //New one
```

Result:
Field **date** content: 0

shouldn't have the `Date.now().toMillis()` value?

**Comment by greenrobot-team** [comment] 2019-02-26 07:15
Can you try making your new property nullable, like `var date: Long?`.

The issue is that ObjectBox will map a null database entry to your non-nullable type, which for `Long` is `0`. If you make the property nullable ObjectBox should set it to `null` instead.

This is essentially #157.

**Comment by greenrobot-team** [comment] 2019-02-26 07:40
Ah, looks like you already found #589. Closing as duplicate. -ut

**Closed by greenrobot-team** 2019-02-26 07:40 UTC
