### ISSUE TITLE
Objectbox: How to initialize ToMany<> relation in kotlin

### ISSUE THREAD

**Issue by mannrecaged** [objectbox/objectbox-java#220] opened 2017-10-18 08:41 UTC
Here is my class:
```Kotlin
@Entity
class EmailMessage () {
    @Id var id: Long = 0
    var subject: String = ""
    var body: String = ""
    lateinit attachments: ToMany<Attachment>
}
```

Usually 'attachments' property has some data before inserting into DB. but accessing 'attachments' before 'put' wouldn't have initialized the property and i don't think its a good idea to 'put' into DB  first just for initialization which is an extra unwanted step i would like to avoid.  

In short, my requirement is to have some data in 'attachments' before inserting into DB. 
Do we have a better way to do it ?, Am i missing something here?

Note: Assigning null also doesn't work

**Comment by mannrecaged** [comment] 2017-10-19 16:48
Update: I was using Roboelectric but the issue didn't surface when i used AndroidInstrumenationTest

**Comment by mannrecaged** [comment] 2017-10-24 18:56
Unit testing on JVM also throws NPE since the property is not initialized. Can you please advise if there is a way to initialize the property during declaration itself?

**Comment by bropane** [comment] 2017-10-27 17:16
Have you found a solution or workaround for this yet? I believe I'm having the same issue as you. I have a Chat class that looks like this: 
```kotlin
@Entity
class DbChat {

    @Id var id: Long = 0

    @Index var mongo_id: String = ""

    lateinit var recipients: ToMany<DbUser>

    lateinit var lastMessage: ToOne<DbMessage>

    @Backlink
    lateinit var messages: ToMany<DbMessage>
}
```
 When I try to do this in a unit test: 
```kotlin
dbModel = DbChat()
val message = DbMessage()
dbModel.lastMessage.target = message
```

I get this:
```
kotlin.UninitializedPropertyAccessException: lateinit property lastMessage has not been initialized

	at com.bernsinc.duels.Modules.Messaging.Data.Model.DbChat.getLastMessage(DbChat.kt:22)
	at com.bernsinc.duels.Modules.Messaging.Data.Messages.Mapper.ChatMapperTest.setUp(ChatMapperTest.kt:34)
```

If I run the same test using AndroidJUnit4,  it passes.

**Comment by crazyxu** [comment] 2017-11-17 02:16
I have the same problem, while i use retrofit, the ToOne<> field cannot been assigned by gson, i must do it manually

**Comment by BukT0p** [comment] 2018-04-12 23:11
This one appears to be related to test build only. Recently I started to write unit test for my repositories and I found that for entity: 

`data class Profession(
        @Id var id: Long = 0,
        @Index var professionID: Int) {
    lateinit var specialtyList: ToMany<Specialty>
}
` 

Whenever I add specialty to specialtyList **jUnit test** gives me:

> kotlin.UninitializedPropertyAccessException: lateinit property specialtyList has not been initialized

But code works fine in the app. I'm using macOS build **io.objectbox:objectbox-macos:1.4.4**

**Comment by karzelekp** [comment] 2018-04-14 14:13
I have a problem with such field (throws UninitializedPropertyAccessException):
```
    @Backlink
    lateinit var verses: ToMany<Verse>
```
But it occures only when I launch application for the first time.
ext.objectboxVersion = '1.4.3'

**Comment by karzelekp** [comment] 2018-04-14 16:29
I updated objectBox to 1.5.0-RC, but nothing has changed.

**Comment by BukT0p** [comment] 2018-04-15 09:15
@greenrobot tried with 1.5.0-RC, now it works for my case, thanks!

**Comment by greenrobot-team** [comment] 2018-04-16 05:57
Please see my comments in #240 for details on why this happens and how to work around it. -ut

**Comment by greenrobot-team** [comment] 2018-04-16 08:39
@karzelekp So your issue is unrelated to unit tests? Please create a new issue and add an example project or code so we can reproduce. This issue is about Android + Kotlin + local unit tests. -ut

**Comment by greenrobot-team** [comment] 2018-04-16 08:47
Closing as @BukT0p reported this (relations in Android + Kotlin + local unit tests) fixed. Please comment and re-open #220 if local unit tests in Android+Kotlin still make problems. -ut

**Closed by greenrobot-team** 2018-04-16 08:47 UTC
Labels: need to investigate
