### ISSUE TITLE
Feature request : Negating a PropertyQueryCondition

### ISSUE THREAD

**Issue by RobbWatershed** [objectbox/objectbox-java#1129] opened 2023-04-19 08:56 UTC
I've been playing with `PropertyQueryCondition`s recently and realized several operators (e.g. `equal` and `oneOf`) have their negative counterparts (respectively `norEqual` and `notOneOf`), whereas string operators are stuck with positive assertions (e.g. `contains`, `endsWith`, `startsWith`). That's an issue I need to address directly to reduce a heavy workaround.

I'd like to suggest two ways of improving that :
- Implement `doesNotContain`, `doesNotEndWith`, `doesNotStartWith` into `Property`
or
- Create `QueryCondition.not()` that would allow to negate any given QueryCondition

Example use case for the latter :
```java
Character_.lastName.equal("lannister", QueryBuilder.StringOrder.CASE_INSENSITIVE)
.and(Character_.firstName.startsWith("ty", QueryBuilder.StringOrder.CASE_INSENSITIVE)) // "Tywin", "Tyrion", "Tytos"

Character_.lastName.equal("lannister", QueryBuilder.StringOrder.CASE_INSENSITIVE)
.and(Character_.firstName.startsWith("ty", QueryBuilder.StringOrder.CASE_INSENSITIVE).not()) // "Cersei", "Jaime", "Lancel"
```

**Comment by greenrobot-team** [comment] 2023-04-24 08:33
Thanks for the request! This is partially a duplicate of #941, so I'm copying the additionally requested conditions there as the other issue has more thumbs ups.

Thumbs up and discuss on #941 instead.

**Closed** 2023-04-24 08:36 UTC
