### ISSUE TITLE
Please allow the release of unused disk space

### ISSUE THREAD

**Issue by LeoK987** [objectbox/objectbox-java#959] opened 2021-03-08 12:47 UTC
I just read the newly updated FAQ entry on disk usage (https://docs.objectbox.io/faq#how-does-objectbox-use-disk-space-and-can-i-reclaim-disk-space).  That's clear - thank you.  But having a way to release disk usage is crucial.

With an app I am developing on Android, a user is expected to test out many data packages before deciding to stay with a couple for a period of perhaps a few months, during or after which time, his process repeats.  The DB's disk usage appears quite high.  With my tests, installing 10 data packages would likely make the DB file to reach 1GB.  So as the user gradually removes unnecessary packages, he would appreciate disk usage gets reduced.  And if he settles on 2 packages, it would be nice if the app only uses 200MB of disk.

I understand the advantages of reusing allocated disk space.  But perhaps the DB can manage to automatically release excessive unused space (say if valid data requires only 200MB, the DB would release space beyond say 250BM, keeping only 20% for further use).

Or perhaps the API provide a function for the app to call to release certain amount of space when a large data package is removed by the end user.

**Comment by greenrobot-team** [comment] 2021-03-09 06:19
Duplicate of #552

**Closed by greenrobot-team** 2021-03-09 06:19 UTC
Labels: feature
