### ISSUE TITLE
BUG: use gradle:3.6.0-rc01 Didn't find class "com.google.android.gms.common.R$string"

### ISSUE THREAD

**Issue by wangzhanxian** [objectbox/objectbox-java#818] opened 2020-01-20 03:57 UTC
```
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/R$string;
        at com.google.android.gms.common.internal.StringResourceValueReader.<init>(Unknown Source:4)
        at com.google.firebase.FirebaseOptions.fromResource(com.google.firebase:firebase-common@@19.3.0:156)
        at com.google.firebase.FirebaseApp.initializeApp(com.google.firebase:firebase-common@@19.3.0:244)
        at com.google.firebase.provider.FirebaseInitProvider.onCreate(com.google.firebase:firebase-common@@19.3.0:51)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2066)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2041)
        at com.google.firebase.provider.FirebaseInitProvider.attachInfo(com.google.firebase:firebase-common@@19.3.0:45)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6774)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6277)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6176)
        at android.app.ActivityThread.access$1200(ActivityThread.java:231)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1839)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7056)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:536)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
```
when I added 'apply plugin: 'io.objectbox'', I ran into a crash ；

**Comment by greenrobot-team** [comment] 2020-01-20 08:50
From what I can gather this is the same issue as #817: for whatever reason all R classes are stripped from the built APK. Closing as a duplicate of #817.

**Closed by greenrobot-team** 2020-01-20 08:50 UTC
