### ISSUE TITLE
Raspberry Pi x64: Unknown os.arch "aarch64" - ObjectBox is defaulting to x64

### ISSUE THREAD

**Issue by aba121** [objectbox/objectbox-java#916] opened 2020-09-28 01:54 UTC
I run my java app on Raspberry Pi x64(OS is centos7 x64)，it just crash...
the error message shown follow, amy help will be appreciated!

ObjectBox Ver: 2.6.0
OS: centos7 x64

Unknown os.arch "aarch64" - ObjectBox is defaulting to x64
Exception in thread "main" java.lang.LinkageError: Loading ObjectBox native library failed: vendor=Oracle Corporation,os=linux,os.arch=aarch64,sun.arch=64,android=false,linux=true
        at io.objectbox.internal.NativeLibraryLoader.<clinit>(NativeLibraryLoader.java:109)
        at io.objectbox.BoxStore.<init>(BoxStore.java:211)
        at io.objectbox.BoxStoreBuilder.build(BoxStoreBuilder.java:382)
        at cn.iyunhao.securer.model.ModelFactory.init(ModelFactory.java:44)
        at cn.iyunhao.securer.SecurerApp.main(SecurerApp.java:24)
Caused by: java.lang.UnsatisfiedLinkError: /root/securer/libobjectbox-jni-linux-x64.so: /root/securer/libobjectbox-jni-linux-x64.so: cannot open shared object file: No such file or directory (Possible cause: architecture word width mismatch)
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1934)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1817)
        at java.lang.Runtime.load0(Runtime.java:809)
        at java.lang.System.load(System.java:1086)
        at io.objectbox.internal.NativeLibraryLoader.<clinit>(NativeLibraryLoader.java:78)
        ... 4 more

**Comment by aba121** [comment] 2020-09-28 05:56
Looking forward to your reply. Thanks! @greenrobot @greenrobot-team

**Comment by greenrobot-team** [comment] 2020-09-28 06:26
Did you add `implementation "io.objectbox:objectbox-linux:$objectboxVersion"` to your depedencies?
https://docs.objectbox.io/java-desktop-apps#native-libraries

**Comment by aba121** [comment] 2020-09-28 07:33
Hi @greenrobot Thanks for your reply!
My Java project build with maven plugin! Here is my depedencies:

<properties>
        <objectboxVersion>2.6.0</objectboxVersion>
    </properties>

<dependencies>
        <dependency>
            <groupId>io.objectbox</groupId>
            <artifactId>objectbox-java</artifactId>
            <version>${objectboxVersion}</version>
        </dependency>

        <dependency>
            <groupId>io.objectbox</groupId>
            <artifactId>objectbox-linux</artifactId>
            <version>${objectboxVersion}</version>
        </dependency>
        <dependency>
            <groupId>io.objectbox</groupId>
            <artifactId>objectbox-macos</artifactId>
            <version>${objectboxVersion}</version>
        </dependency>
        <dependency>
            <groupId>io.objectbox</groupId>
            <artifactId>objectbox-windows</artifactId>
            <version>${objectboxVersion}</version>
        </dependency>

    </dependencies>

<pluginRepositories>
        <pluginRepository>
            <id>bintray-objectbox-objectbox</id>
            <name>bintray-plugins</name>
            <url>https://dl.bintray.com/objectbox/objectbox</url>
        </pluginRepository>
    </pluginRepositories>

<build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>versions-maven-plugin</artifactId>
                <version>2.7</version>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                    <encoding>${project.build.sourceEncoding}</encoding>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>io.objectbox</groupId>
                            <artifactId>objectbox-processor</artifactId>
                            <version>${objectboxVersion}</version>
                        </path>
                    </annotationProcessorPaths>
                    <annotationProcessors>
                        <annotationProcessor>io.objectbox.processor.ObjectBoxProcessorShim</annotationProcessor>
                    </annotationProcessors>
                    <compilerArgs>
                        <arg>-Aobjectbox.modelPath=${project.basedir}/models/models.json</arg>
                    </compilerArgs>
                </configuration>
            </plugin>
            <plugin>
                <groupId>io.objectbox</groupId>
                <artifactId>objectbox-maven-plugin</artifactId>
                <version>1.2.0</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>transform</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <debug>false</debug>
                </configuration>
            </plugin>
            ...
        </plugins>

    </build>

In my jar, I saw  
/native/
           libobjectbox-jni-linux-x64.so
           libobjectbox-jni-macos-x64.dylib
           objectbox-jni-windows-x64.dll
           objectbox-jni-windows-x86.dll

After excuting java -jar xxx.jar
I saw libobjectbox-jni-linux-x64.so showed.

`private static String getCpuArch() {
        String osArch = System.getProperty("os.arch");
        String cpuArch = null;
        if (osArch != null) {
            osArch = osArch.toLowerCase();
            if (osArch.equalsIgnoreCase("amd64") || osArch.equalsIgnoreCase("x86_64")) {
                cpuArch = "x64";
            } else if (osArch.equalsIgnoreCase("x86")) {
                cpuArch = "x86";
            } /*else if (osArch.equalsIgnoreCase("aarch64")) {
                cpuArch = "aarch64";
            } */else if (osArch.startsWith("arm")) {
                switch (osArch) {
                    case "armv7":
                    case "armv7l":
                    case "armeabi-v7a": // os.arch "armeabi-v7a" might be Android only, but let's try anyway...
                        cpuArch = "armv7";
                        break;
                    case "arm64-v8a":
                        cpuArch = "arm64";
                        break;
                    case "armv6":
                        cpuArch = "armv6";
                        break;
                    default:
                        cpuArch = "armv6";  // Lowest version we support
                        System.err.println("Unknown os.arch \"" + osArch + "\" - ObjectBox is defaulting to " + cpuArch);
                        break;
                }
            }
        }
        if (cpuArch == null) {
            String sunArch = System.getProperty("sun.arch.data.model");
            cpuArch = "32".equals(sunArch) ? "x86" : "x64";
            System.err.println("Unknown os.arch \"" + osArch + "\" - ObjectBox is defaulting to " + cpuArch);
        }
        return cpuArch;
    }`

It seems that we need a lib build for aarch64 arch!

**Comment by greenrobot-team** [comment] 2020-09-28 08:00
Sorry, you wrote `OS is centos7 x64` so I assumed it was x86, not ARM.

This is then a duplicate of #657, please vote for that issue.

**Closed by greenrobot-team** 2020-09-28 08:00 UTC
Labels: bug, more info required

**Comment by aba121** [comment] 2020-09-28 12:25
@greenrobot Sorry. I didn’t see it! Hope this feature released soon!
