### ISSUE TITLE
Update query when related entities change

### ISSUE THREAD

**Issue by alekop** [objectbox/objectbox-java#387] opened 2018-03-13 05:24 UTC
Is there a way for an observable query to detect when a related entity changes, and notify its subscribers? The following uses a one-to-one relationship between a person and an address. I would like the person query to be notified when a person's address changes.

```
@Entity
data class Person(@Id val id: Long = 0) {
    lateinit var homeAddress: ToOne<Address>
}

@Entity
data class Address(@Id var id: Long = 0,
    val street: String
)

// Build a query for the parent
val query = boxStore.boxFor<Person>().query().build()
query.find()

// I want to be notified when the address changes
query.subscribe(...)

// Update the relationship
person.homeAddress.target = Address(street= "...")
boxStore.boxFor<Address>.put(newAddress) // persists, but the person query does not get notified
```

This updates the address box as expected, but the person query is not notified. Any way to accomplish that?

**Comment by greenrobot-team** [comment] 2018-03-13 12:59
The query is set up to only listen for changes of the entity used to build the query. However, you could just add another observer on the `Address` entity:
`boxStore.subscribe(Address.class).on(...).observer(..)`
-ut

**Comment by greenrobot-team** [comment] 2018-03-13 13:20
Also see #300. -ut

**Comment by Ekalips** [comment] 2018-03-21 12:04
I vote up for this issue. 
Maybe there is some possibility to add some kind of `.deep()` into subscription builder? So subscription will track not only main entity updates but also related data changes.

**Comment by squeeish** [comment] 2018-04-06 09:41
This will be awesome for LiveData too

**Comment by squeeish** [comment] 2018-08-20 15:05
Is this in 2.1.0?

**Comment by amgadserry** [comment] 2019-03-18 14:42
is there any plans to implement this feature or even a workaround ? @greenrobot-team

**Comment by greenrobot-team** [comment] 2019-03-19 07:36
@amgadserry A workaround is mentioned in the first comment: https://github.com/objectbox/objectbox-java/issues/387#issuecomment-372656467

-Uwe

**Comment by amgadserry** [comment] 2019-03-19 07:58
@greenrobot-team thanks i was using the current code 
```
    fun getPopulatedAccounts(): Observable<List<AccountEntity>> {
        val zipper: BiFunction<
                List<AccountEntity>,
                List<RequestEntity>,
                List<AccountEntity>> = BiFunction { accounts, _ -> accounts }

        val accountsQueryObservable = RxQuery.observable(accountsDao.findAll())

        val requestsQueryObservable = RxQuery.observable(requestDao.findAll())

        return Observable.combineLatest(accountsQueryObservable, requestsQueryObservable, zipper)
    }
```
I use rxjava so I thought you might already have smth for that
Thanks for the great effort

**Comment by amgadserry** [comment] 2019-03-19 08:37
@greenrobot-team thanks i was using the current code so is there a way to do it on a query instead of the box itself as i cannot create a query after .subscribe on box
```
    fun getPopulatedAccounts(): Observable<List<AccountEntity>> {
        val zipper: BiFunction<
                List<AccountEntity>,
                List<RequestEntity>,
                List<AccountEntity>> = BiFunction { accounts, _ -> 
                    accounts.forEach { it.requests.reset() } // requests is a backlink so it is cached
                    accounts
                }

        val accountsQueryObservable = RxQuery.observable(accountsDao.findAll())

        val requestsQueryObservable = RxQuery.observable(requestDao.findAll())

        return Observable.combineLatest(accountsQueryObservable, requestsQueryObservable, zipper)
    }
```
notice the manual reset for backlinks 
the problem gets messier when u r using smth like Diffutil which then you would need smth like this instead because resetting the requests would simply change both old and new version which would result in ur data not updating due to the diffutil thinking that objects are the same
```
accounts.map {
                val _copy = it.copy()
                _copy.requests.reset()
                _copy
            }
```
Thanks for the great effort u put in this engine though it's amazing !!

**Comment by amgadserry** [comment] 2019-03-19 09:01
@greenrobot-team here is the final solution i went with 
```
    fun getPopulatedAccounts(): Observable<List<AccountEntity>> {
        val zipper: BiFunction<
                Any,
                Any,
                List<AccountEntity>> = BiFunction { _, _ -> 
                    accountsDoa.findAll {
                        eager(Account_.requests)
                    }.find()
                }

        val accountsObservable = RxBoxStore.observable<Account>(accountsDoa.store)

        val requestsObservable = RxBoxStore.observable<RequestEntity>(requestDao.store)

        return Observable.combineLatest(accountsObservable, requestsObservable, zipper)
    }
```
let me know if there are a better workaround for rxjava. Thanks

**Comment by greenrobot-team** [comment] 2020-09-08 14:19
Duplicate of #268

**Closed by greenrobot-team** 2020-09-08 14:19 UTC
Labels: feature
