### ISSUE TITLE
io.objectbox.exception.DbSchemaException: Cannot change the following flags for Property...

### ISSUE THREAD

**Issue by glenhsi** [objectbox/objectbox-java#1088] opened 2022-07-23 12:35 UTC
io.objectbox.exception.DbSchemaException: Cannot change the following flags for Property msgId (4, Long) (Message) from 12 to 8 (problematic flags: 4). Consider creating a new property instead. Please check the docs on data model migration and UIDs.
        at io.objectbox.BoxStore.nativeCreateWithFlatOptions(Native Method)
        at io.objectbox.BoxStore.<init>(BoxStore.java:265)
        at io.objectbox.BoxStoreBuilder.build(BoxStoreBuilder.java:516)

I just upgrade objectbox plugin  from v2.9.1 to v3.2.0, then reinstall my app, crash with that log, at the model files,  the flags of the message table is changed,from 12 to 8,  I want to know how to fix it, thanks

**Comment by greenrobot-team** [comment] 2022-07-25 08:38
Is it possible that you forgot to also update all other ObjectBox dependencies to 3.2.0? (Note, there is already 3.2.1 available.) This looks like you only updated the Gradle plugin. I can not reproduce this.

**Comment by glenhsi** [comment] 2022-07-27 03:32
thanks for your response,your reply helped me,my issue is fixed,thanks very much~

**Comment by greenrobot-team** [comment] 2022-08-01 06:25
Thanks for reporting back! Closing this issue as it has been resolved.

**Closed by greenrobot-team** 2022-08-01 06:25 UTC
