### ISSUE TITLE
After I add Uid Build the project, no prompt error: [ObjectBox] Uid operations for entity XX.

### ISSUE THREAD

**Issue by Jayqiu** [objectbox/objectbox-java#439] opened 2018-04-28 02:32 UTC
After I add Uid Build the project, no prompt error: [ObjectBox] Uid operations for entity XX. But prompt org. Gradle. API. The tasks. TaskExecutionException: Execution failed for task ': app: compileDebugJavaWithJavac'.

Android studio 3.1.2.    gradle-4.4-all。

**Comment by greenrobot-team** [comment] 2018-04-30 13:18
Can you please post the full Gradle output? Or share a small example project that reproduces the issue. -ut

**Comment by greenrobot-team** [comment] 2018-05-07 10:04
Closing. Please re-open if more details (see my comment) become available. -ut

**Closed by greenrobot-team** 2018-05-07 10:04 UTC
Labels: more info required

**Comment by damonbakker** [comment] 2019-08-09 15:49
I just had the same issue. 
It must have something to do with the project config I think.

I came from DaoCompat and it's really hit or mess whether objectbox will give me an error or not atm.
I added @Uid to these 2 properties.
```
    @Uid
    private long remoteId;
    @Uid
    private long clientId;
```

This was to try and prevent other errors I had when saving object versions of Long.
There is no prompt for a unique ID.

It silently fails then continues to go to the JavaCompiler, which then fails due to all the generated DAOs missing for me.
I don't really know what could be causing this honestly, I'm pretty deep in refactoring through daocompat.

Is there a way to change the property type without having to force a build error?
I really really liked how I could update the schemaversion on greendao, forcing the entire database to reset. 

I have no need to presist data currently, can I go around this @Uid maybe?

Thanks in advance.

**Comment by greenrobot-team** [comment] 2019-08-12 07:14
@damonbakker To completely reset you can delete the `default.json` model file and a new one will be generated. But you have to delete any existing database files before building BoxStore with the new model, e.g. using `BoxStore.deleteAllFiles(<dir>)`.
