### ISSUE TITLE
How to set param 'limit' by query.subscribe..on.observer

### ISSUE THREAD

**Issue by AstaTus** [objectbox/objectbox-java#405] opened 2018-03-24 08:56 UTC
I can set limit by query.find(offset, limit)
but I want use Rx style to query database,  and I can't find way to set limit param,
so what can I do?

**Comment by greenrobot-team** [comment] 2018-03-26 08:53
This is currently not supported, but was already requested in #303. 

Duplicate of 303#.
-ut

**Closed by greenrobot-team** 2018-03-26 08:53 UTC
