### ISSUE TITLE
Error when generate signed bundle with ArrayIndexOutOfBoundsException 

### ISSUE THREAD

**Issue by tierian** [objectbox/objectbox-java#1112] opened 2023-02-06 10:07 UTC
On Android Studio, when I generate signed bundle,
if I use Android gradle plugin ver.7.4, it gets error with objectbox file 
"java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 18"

If I use Android gradle plugin ver.7.3 or earlier, generate-signed-bundle will be completed with no problem.

![2023-02-06_18h56_53](https://user-images.githubusercontent.com/63704340/216941795-8a8799b2-8c30-4de8-8544-bb12e52daea2.png)

- Android Studio Electric Eel | 2022.1.1 Patch 1
- objectbox-gradle-plugin:3.5.1
- Kotlin
- Android Gradle Plugin ver.7.4. Gradle version 7.5
- Build > Generate signed bundle > Android app bundle (while creating, gets error)

**Comment by greenrobot-team** [comment] 2023-02-06 10:30
Thanks for reporting! I can't reproduce this with our (internal) TV program app.

Can you share the stack trace? E.g. in the Build tool window look for the text output (should open right next to the error message you have shown above once you click on it).

**Comment by tierian** [comment] 2023-02-06 11:04
```
AGPBI: {"kind":"error","text":"java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 18","sources":[{"file":"C:\\Users\\tierian\\AndroidStudioProjects\\myproject1\\app\\build\\intermediates\\asm_instrumented_project_classes\\release\\com\\myapp\\ObjectBox$saveAutoBackupL$2.class"}],"tool":"R8"}

> Task :app:minifyReleaseWithR8 FAILED
```

**Comment by greenrobot-team** [comment] 2023-02-06 11:17
Thanks. I guess you have already tried to Build > Rebuild Project?

The info is not enough for us to act upon. Can you try running the bundle task with the `--stacktraces` option?

**Comment by tierian** [comment] 2023-02-06 11:55
I got this message with --stacktrace

`Compilation failed to complete, position: Lcom/myapp/ObjectBox$startAdminMode$2;invokeSuspend(Ljava/lang/Object;)Ljava/lang/Object;, origin: C:\Users\tierian\AndroidStudioProjects\myproject1\app\build\intermediates\asm_instrumented_project_classes\release\com\myapp\ObjectBox$startAdminMode$2.class`

**Comment by greenrobot-team** [comment] 2023-03-22 07:59
That method mentions [Admin](https://docs.objectbox.io/data-browser). Maybe check if your dependencies include `objectbox-android` and `objectbox-android-objectbrowser` at the same time, they should not (e.g. see [the setup steps](https://docs.objectbox.io/data-browser#setup)).

**Comment by tierian** [comment] 2023-03-23 07:35
Hi, thanks for your reply.

Objectbox admin wasn't the problem.
The problem was R8 proguard. I added "-keep class com.myapp.ObjectBox**" to proguard-rules.pro and at last I could generate app bundle. This problem wasn't occur gradle plugin ver.7.3 or eariler. They changed something on proguard, I guess.

Anyway, thank you for your help.

**Comment by greenrobot-team** [comment] 2023-03-27 10:47
Thanks! Closing this then.

**Closed by greenrobot-team** 2023-03-27 10:47 UTC
Labels: bug
